// This file is generated by scripts/generate-api-contract.mjs. Do not edit.

import Foundation

struct CarrierDetectionRequest: Codable, Equatable, Hashable, Sendable {
    var trackingNumber: String
}

struct CarrierDetectionResponse: Codable, Equatable, Hashable, Sendable {
    var trackingNumber: String
    var amazonShippingStatus: CarrierDetectionResponseAmazonShippingStatus? = nil
    var carrier: CarrierID
}

struct AccountExportResponse: Codable, Equatable, Hashable, Sendable {
    var exportedAt: String
    var account: AccountExportAccount
    var packages: [Parcel]
    var friends: FriendsExport? = nil
}

struct DeleteAccountRequest: Codable, Equatable, Hashable, Sendable {
    var confirmation: String
}

struct CarrierID: RawRepresentable, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    let rawValue: String

    init(rawValue: String) {
        self.rawValue = rawValue
    }

    static let swissPost = CarrierID(rawValue: "swiss-post")
    static let swissPostCargo = CarrierID(rawValue: "swiss-post-cargo")
    static let quickpac = CarrierID(rawValue: "quickpac")
    static let planzer = CarrierID(rawValue: "planzer")
    static let aliexpress = CarrierID(rawValue: "aliexpress")
    static let sunyou = CarrierID(rawValue: "sunyou")
    static let hermes = CarrierID(rawValue: "hermes")
    static let springGDS = CarrierID(rawValue: "spring-gds")
    static let postlogistics = CarrierID(rawValue: "postlogistics")
    static let dachser = CarrierID(rawValue: "dachser")
    static let dhl = CarrierID(rawValue: "dhl")
    static let dhlEcommerce = CarrierID(rawValue: "dhl-ecommerce")
    static let ups = CarrierID(rawValue: "ups")
    static let amazonLogistics = CarrierID(rawValue: "amazon-logistics")
    static let amazonShipping = CarrierID(rawValue: "amazon-shipping")
    static let fedex = CarrierID(rawValue: "fedex")
    static let glsCh = CarrierID(rawValue: "gls-ch")
    static let dpd = CarrierID(rawValue: "dpd")
    static let dpdFr = CarrierID(rawValue: "dpd-fr")
    static let mondialRelay = CarrierID(rawValue: "mondial-relay")
    static let relaisColis = CarrierID(rawValue: "relais-colis")
    static let laPoste = CarrierID(rawValue: "la-poste")
    static let chronopost = CarrierID(rawValue: "chronopost")
    static let glsFr = CarrierID(rawValue: "gls-fr")
    static let colisPrive = CarrierID(rawValue: "colis-prive")
    static let geodis = CarrierID(rawValue: "geodis")
    static let colisweb = CarrierID(rawValue: "colisweb")
    static let cChezVous = CarrierID(rawValue: "c-chez-vous")
    static let heppner = CarrierID(rawValue: "heppner")
    static let ciblex = CarrierID(rawValue: "ciblex")
    static let paack = CarrierID(rawValue: "paack")
    static let asendia = CarrierID(rawValue: "asendia")
    static let shipup = CarrierID(rawValue: "shipup")
    static let indiaPost = CarrierID(rawValue: "india-post")
    static let hermesDe = CarrierID(rawValue: "hermes-de")
    static let glsDe = CarrierID(rawValue: "gls-de")
    static let delivengo = CarrierID(rawValue: "delivengo")
    static let anPost = CarrierID(rawValue: "an-post")
    static let aramex = CarrierID(rawValue: "aramex")
    static let australiaPost = CarrierID(rawValue: "australia-post")
    static let austrianPost = CarrierID(rawValue: "austrian-post")
    static let blueDart = CarrierID(rawValue: "blue-dart")
    static let bpost = CarrierID(rawValue: "bpost")
    static let bringPosten = CarrierID(rawValue: "bring-posten")
    static let brt = CarrierID(rawValue: "brt")
    static let canadaPost = CarrierID(rawValue: "canada-post")
    static let canpar = CarrierID(rawValue: "canpar")
    static let chinaPost = CarrierID(rawValue: "china-post")
    static let correiosBr = CarrierID(rawValue: "correios-br")
    static let correosChile = CarrierID(rawValue: "correos-chile")
    static let correosExpress = CarrierID(rawValue: "correos-express")
    static let correosSpain = CarrierID(rawValue: "correos-spain")
    static let ctt = CarrierID(rawValue: "ctt")
    static let cttExpress = CarrierID(rawValue: "ctt-express")
    static let delhivery = CarrierID(rawValue: "delhivery")
    static let dtdc = CarrierID(rawValue: "dtdc")
    static let ecoscooting = CarrierID(rawValue: "ecoscooting")
    static let estafeta = CarrierID(rawValue: "estafeta")
    static let evri = CarrierID(rawValue: "evri")
    static let fourPx = CarrierID(rawValue: "four-px")
    static let gofo = CarrierID(rawValue: "gofo")
    static let hongkongPost = CarrierID(rawValue: "hongkong-post")
    static let inpost = CarrierID(rawValue: "inpost")
    static let jAndT = CarrierID(rawValue: "j-and-t")
    static let japanPost = CarrierID(rawValue: "japan-post")
    static let jdLogistics = CarrierID(rawValue: "jd-logistics")
    static let koreaPost = CarrierID(rawValue: "korea-post")
    static let landmarkGlobal = CarrierID(rawValue: "landmark-global")
    static let mrw = CarrierID(rawValue: "mrw")
    static let nacex = CarrierID(rawValue: "nacex")
    static let ninjaVan = CarrierID(rawValue: "ninja-van")
    static let nzPost = CarrierID(rawValue: "nz-post")
    static let oldDominion = CarrierID(rawValue: "old-dominion")
    static let ontrac = CarrierID(rawValue: "ontrac")
    static let packeta = CarrierID(rawValue: "packeta")
    static let parcelforce = CarrierID(rawValue: "parcelforce")
    static let pocztaPolska = CarrierID(rawValue: "poczta-polska")
    static let posMalaysia = CarrierID(rawValue: "pos-malaysia")
    static let posteItaliane = CarrierID(rawValue: "poste-italiane")
    static let posti = CarrierID(rawValue: "posti")
    static let postnord = CarrierID(rawValue: "postnord")
    static let purolator = CarrierID(rawValue: "purolator")
    static let royalMail = CarrierID(rawValue: "royal-mail")
    static let seur = CarrierID(rawValue: "seur")
    static let sfExpress = CarrierID(rawValue: "sf-express")
    static let singaporePost = CarrierID(rawValue: "singapore-post")
    static let speeDee = CarrierID(rawValue: "spee-dee")
    static let speedx = CarrierID(rawValue: "speedx")
    static let sto = CarrierID(rawValue: "sto")
    static let thailandPost = CarrierID(rawValue: "thailand-post")
    static let theCourierGuy = CarrierID(rawValue: "the-courier-guy")
    static let tipsa = CarrierID(rawValue: "tipsa")
    static let tnt = CarrierID(rawValue: "tnt")
    static let ukrposhta = CarrierID(rawValue: "ukrposhta")
    static let uniuni = CarrierID(rawValue: "uniuni")
    static let usps = CarrierID(rawValue: "usps")
    static let yamato = CarrierID(rawValue: "yamato")
    static let yanwen = CarrierID(rawValue: "yanwen")
    static let yto = CarrierID(rawValue: "yto")
    static let yunda = CarrierID(rawValue: "yunda")
    static let yunexpress = CarrierID(rawValue: "yunexpress")
    static let zto = CarrierID(rawValue: "zto")
    static let internationalPost = CarrierID(rawValue: "intl-post")
    static let unknown = CarrierID(rawValue: "unknown")

    static let allCases: [CarrierID] = [
        .swissPost,
        .swissPostCargo,
        .quickpac,
        .planzer,
        .aliexpress,
        .sunyou,
        .hermes,
        .springGDS,
        .postlogistics,
        .dachser,
        .dhl,
        .dhlEcommerce,
        .ups,
        .amazonLogistics,
        .amazonShipping,
        .fedex,
        .glsCh,
        .dpd,
        .dpdFr,
        .mondialRelay,
        .relaisColis,
        .laPoste,
        .chronopost,
        .glsFr,
        .colisPrive,
        .geodis,
        .colisweb,
        .cChezVous,
        .heppner,
        .ciblex,
        .paack,
        .asendia,
        .shipup,
        .indiaPost,
        .hermesDe,
        .glsDe,
        .delivengo,
        .anPost,
        .aramex,
        .australiaPost,
        .austrianPost,
        .blueDart,
        .bpost,
        .bringPosten,
        .brt,
        .canadaPost,
        .canpar,
        .chinaPost,
        .correiosBr,
        .correosChile,
        .correosExpress,
        .correosSpain,
        .ctt,
        .cttExpress,
        .delhivery,
        .dtdc,
        .ecoscooting,
        .estafeta,
        .evri,
        .fourPx,
        .gofo,
        .hongkongPost,
        .inpost,
        .jAndT,
        .japanPost,
        .jdLogistics,
        .koreaPost,
        .landmarkGlobal,
        .mrw,
        .nacex,
        .ninjaVan,
        .nzPost,
        .oldDominion,
        .ontrac,
        .packeta,
        .parcelforce,
        .pocztaPolska,
        .posMalaysia,
        .posteItaliane,
        .posti,
        .postnord,
        .purolator,
        .royalMail,
        .seur,
        .sfExpress,
        .singaporePost,
        .speeDee,
        .speedx,
        .sto,
        .thailandPost,
        .theCourierGuy,
        .tipsa,
        .tnt,
        .ukrposhta,
        .uniuni,
        .usps,
        .yamato,
        .yanwen,
        .yto,
        .yunda,
        .yunexpress,
        .zto,
        .internationalPost,
        .unknown,
    ]

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        rawValue = try container.decode(String.self)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    var id: String { rawValue }
}

enum TrackingStage: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case pending
    case registered
    case accepted
    case inTransit = "in_transit"
    case outForDelivery = "out_for_delivery"
    case delivered
    case customs
    case failedAttempt = "failed_attempt"
    case readyForPickup = "ready_for_pickup"
    case returned
    case exception

    var id: String { rawValue }
}

enum SyncStatus: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case pending
    case syncing
    case ok
    case waiting
    case error
    case unsupported

    var id: String { rawValue }
}

struct TrackingEvent: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var packageID: UUID
    var stage: TrackingStage
    var description: String
    var location: String? = nil
    var occurredAt: String

    private enum CodingKeys: String, CodingKey {
        case id
        case packageID = "packageId"
        case stage
        case description
        case location
        case occurredAt
    }
}

struct Parcel: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var trackingNumber: String
    var label: String
    var carrier: CarrierID
    var createdAt: String
    var expectedDelivery: String? = nil
    var lastStatusText: String? = nil
    var lastSyncedAt: String? = nil
    var syncStatus: SyncStatus
    var syncError: String? = nil
    var trackingURL: String? = nil
    var dpdPostcode: String? = nil
    var carrierData: CarrierData? = nil
    var archivedAt: String? = nil
    var notificationsMuted: Bool
    var trackingEvents: [TrackingEvent] = []

    private enum CodingKeys: String, CodingKey {
        case id
        case trackingNumber
        case label
        case carrier
        case createdAt
        case expectedDelivery
        case lastStatusText
        case lastSyncedAt
        case syncStatus
        case syncError
        case trackingURL = "trackingUrl"
        case dpdPostcode
        case carrierData
        case archivedAt
        case notificationsMuted
        case trackingEvents
    }
}

struct PackageListResponse: Codable, Equatable, Hashable, Sendable {
    var packages: [Parcel]
}

struct CreatePackageResponse: Codable, Equatable, Hashable, Sendable {
    var package: Parcel
    var jobIDs: [UUID]

    private enum CodingKeys: String, CodingKey {
        case package
        case jobIDs = "jobIds"
    }
}

struct CreatePackageRequest: Codable, Equatable, Hashable, Sendable {
    var trackingNumber: String
    var label: String? = nil
    var carrier: CarrierID? = nil
    var trackingURL: String? = nil
    var dpdPostcode: String? = nil

    private enum CodingKeys: String, CodingKey {
        case trackingNumber
        case label
        case carrier
        case trackingURL = "trackingUrl"
        case dpdPostcode
    }
}

struct RenamePackageRequest: Codable, Equatable, Hashable, Sendable {
    var label: String
}

struct ChangePackageCarrierRequest: Codable, Equatable, Hashable, Sendable {
    var carrier: CarrierID
    var trackingURL: String? = nil
    var dpdPostcode: String? = nil

    private enum CodingKeys: String, CodingKey {
        case carrier
        case trackingURL = "trackingUrl"
        case dpdPostcode
    }
}

struct ChangePackageCarrierResponse: Codable, Equatable, Hashable, Sendable {
    var package: Parcel
    var jobIDs: [UUID]

    private enum CodingKeys: String, CodingKey {
        case package
        case jobIDs = "jobIds"
    }
}

struct PackageNotificationRequest: Codable, Equatable, Hashable, Sendable {
    var muted: Bool
}

struct QueueResponse: Codable, Equatable, Hashable, Sendable {
    var queued: Bool
    var pending: Int
    var jobIDs: [UUID]

    private enum CodingKeys: String, CodingKey {
        case queued
        case pending
        case jobIDs = "jobIds"
    }
}

struct OKResponse: Codable, Equatable, Hashable, Sendable {
    var ok: Bool
}

struct ErrorResponse: Codable, Equatable, Hashable, Sendable {
    var error: String
    var packageID: UUID? = nil

    private enum CodingKeys: String, CodingKey {
        case error
        case packageID = "packageId"
    }
}

struct PushConfigResponse: Codable, Equatable, Hashable, Sendable {
    var available: Bool
    var publicKey: String? = nil
}

enum NotificationStage: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case registered
    case accepted
    case inTransit = "in_transit"
    case customs
    case exception
    case outForDelivery = "out_for_delivery"
    case failedAttempt = "failed_attempt"
    case readyForPickup = "ready_for_pickup"
    case delivered
    case returned

    var id: String { rawValue }
}

struct NotificationPreferences: Codable, Equatable, Hashable, Sendable {
    var enabledStages: [NotificationStage]
    var quietHoursStart: String? = nil
    var quietHoursEnd: String? = nil
    var timezone: String
}

struct PushSubscriptionKeys: Codable, Equatable, Hashable, Sendable {
    var p256dh: String
    var auth: String
}

struct PushSubscriptionRequest: Codable, Equatable, Hashable, Sendable {
    var endpoint: String
    var keys: PushSubscriptionKeys
    var locale: NativePushLocale? = nil
}

struct DeletePushSubscriptionRequest: Codable, Equatable, Hashable, Sendable {
    var endpoint: String
}

struct PushSubscriptionResponse: Codable, Equatable, Hashable, Sendable {
    var ok: Bool
    var testSent: Bool
}

enum NativePushEnvironment: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case development
    case production

    var id: String { rawValue }
}

enum NativePushLocale: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case en
    case de
    case fr
    case it
    case es
    case pt
    case pl

    var id: String { rawValue }
}

struct NativePushDeviceRequest: Codable, Equatable, Hashable, Sendable {
    var token: String
    var installationID: UUID? = nil
    var environment: NativePushEnvironment
    var locale: NativePushLocale
    var deviceName: String? = nil
    var sendTest: Bool

    private enum CodingKeys: String, CodingKey {
        case token
        case installationID = "installationId"
        case environment
        case locale
        case deviceName
        case sendTest
    }
}

struct DeleteNativePushDeviceRequest: Codable, Equatable, Hashable, Sendable {
    var token: String
}

struct LiveActivityDeviceRequest: Codable, Equatable, Hashable, Sendable {
    var installationID: UUID
    var token: String
    var environment: NativePushEnvironment
    var locale: NativePushLocale
    var revocationToken: String? = nil

    private enum CodingKeys: String, CodingKey {
        case installationID = "installationId"
        case token
        case environment
        case locale
        case revocationToken
    }
}

struct DeleteLiveActivityDeviceRequest: Codable, Equatable, Hashable, Sendable {
    var installationID: UUID

    private enum CodingKeys: String, CodingKey {
        case installationID = "installationId"
    }
}

struct LiveActivityUpdateTokenRequest: Codable, Equatable, Hashable, Sendable {
    var installationID: UUID
    var activityID: String
    var parcelID: UUID
    var token: String
    var environment: NativePushEnvironment
    var locale: NativePushLocale

    private enum CodingKeys: String, CodingKey {
        case installationID = "installationId"
        case activityID = "activityId"
        case parcelID = "parcelId"
        case token
        case environment
        case locale
    }
}

struct DeleteLiveActivityUpdateTokenRequest: Codable, Equatable, Hashable, Sendable {
    var installationID: UUID
    var activityID: String

    private enum CodingKeys: String, CodingKey {
        case installationID = "installationId"
        case activityID = "activityId"
    }
}

enum SyncJobStatus: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case queued
    case running
    case succeeded
    case failed

    var id: String { rawValue }
}

struct SyncJobListResponse: Codable, Equatable, Hashable, Sendable {
    var jobs: [SyncJobResponse]
}

struct SyncJobResponse: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var status: SyncJobStatus
    var packageID: UUID? = nil
    var requestedAt: String
    var startedAt: String? = nil
    var completedAt: String? = nil
    var result: SyncSummary? = nil
    var error: String? = nil

    private enum CodingKeys: String, CodingKey {
        case id
        case status
        case packageID = "packageId"
        case requestedAt
        case startedAt
        case completedAt
        case result
        case error
    }
}

struct SyncSummary: Codable, Equatable, Hashable, Sendable {
    var checked: Int? = nil
    var updated: Int? = nil
    var waiting: Int? = nil
    var errors: Int? = nil
    var unsupported: Int? = nil
    var superseded: Int? = nil
    var notificationsSent: Int? = nil
    var notificationErrors: Int? = nil
    var subscriptionsExpired: Int? = nil
}

struct HealthResponse: Codable, Equatable, Hashable, Sendable {
    var ok: Bool
}

struct UpdatePushSubscriptionLocaleRequest: Codable, Equatable, Hashable, Sendable {
    var endpoint: String
    var locale: NativePushLocale
}

enum FriendStamp: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case first
    case ten
    case connected
    case express
    case acrossBorders
    case aroundWorld
    case theRegular
    case rightNextDoor
    case worthTheWait
    case busyDoorstep
    case pickedUp
    case homeForHolidays

    var id: String { rawValue }
}

struct FriendStats: Codable, Equatable, Hashable, Sendable {
    var deliveredCount: Int
    var averageDays: Int? = nil
    var stamps: [FriendStamp]
}

struct FriendProfile: Codable, Equatable, Hashable, Sendable {
    var nickname: String
    var shareStats: Bool
    var shareArrival: Bool
}

struct FriendCard: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var nickname: String
    var stats: FriendStats? = nil
    var arrivedThisWeek: Bool? = nil
}

struct FriendsSnapshot: Codable, Equatable, Hashable, Sendable {
    var profile: FriendProfile? = nil
    var ownCard: FriendCard? = nil
    var friends: [FriendCard]
}

enum FriendsAction: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case saveProfile = "save_profile"
    case createInvite = "create_invite"
    case revokeInvite = "revoke_invite"
    case revokePreviousInvites = "revoke_previous_invites"
    case previewInvite = "preview_invite"
    case acceptInvite = "accept_invite"
    case removeFriend = "remove_friend"
    case disable
    case acknowledgeFriend = "acknowledge_friend"

    var id: String { rawValue }
}

struct FriendsActionRequest: Codable, Equatable, Hashable, Sendable {
    var action: FriendsAction
    var nickname: String? = nil
    var shareStats: Bool? = nil
    var shareArrival: Bool? = nil
    var code: String? = nil
    var friendID: UUID? = nil

    private enum CodingKeys: String, CodingKey {
        case action
        case nickname
        case shareStats
        case shareArrival
        case code
        case friendID = "friendId"
    }
}

struct FriendsActionResponse: Codable, Equatable, Hashable, Sendable {
    var snapshot: FriendsSnapshot? = nil
    var inviteCode: String? = nil
    var previewID: String? = nil
    var expiresAt: String? = nil
    var previewNickname: String? = nil
    var invitationState: FriendsActionResponseInvitationState? = nil
    var acceptedFriend: FriendCard? = nil
    var previousInviteCount: Int? = nil

    private enum CodingKeys: String, CodingKey {
        case snapshot
        case inviteCode
        case previewID = "previewId"
        case expiresAt
        case previewNickname
        case invitationState
        case acceptedFriend
        case previousInviteCount
    }
}

struct FriendExportConnection: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var nickname: String
}

struct FriendsExport: Codable, Equatable, Hashable, Sendable {
    var profile: FriendProfile? = nil
    var connections: [FriendExportConnection]
}

struct FriendUpdate: Codable, Equatable, Hashable, Sendable {
    var friendID: UUID
    var nickname: String

    private enum CodingKeys: String, CodingKey {
        case friendID = "friendId"
        case nickname
    }
}

struct FriendsActivity: Codable, Equatable, Hashable, Sendable {
    var updates: [FriendUpdate]
}

struct RevokeLiveActivityDeviceRequest: Codable, Equatable, Hashable, Sendable {
    var installationID: UUID
    var revocationToken: String

    private enum CodingKeys: String, CodingKey {
        case installationID = "installationId"
        case revocationToken
    }
}

enum CarrierDetectionResponseAmazonShippingStatus: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case available
    case expired
    case notFound = "not-found"
    case unavailable

    var id: String { rawValue }
}

struct AccountExportAccount: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var email: String? = nil
}

struct CarrierData: Codable, Equatable, Hashable, Sendable {
    var activeTrackingCarrier: CarrierID? = nil
    var activeTrackingNumber: String? = nil
    var originalPackageID: UUID? = nil
    var originalCarrier: CarrierID? = nil
    var originalTrackingNumber: String? = nil
    var originalTrackingURL: String? = nil
    var trackingProvider: String? = nil
    var autoChangedFrom: CarrierID? = nil
    var autoChangedTo: CarrierID? = nil
    var autoChangedAt: String? = nil
    var senderName: String? = nil
    var swissPostReady: Bool? = nil
    var expectedDeliveryFrom: String? = nil
    var pickupPoint: String? = nil
    var receiverName: String? = nil
    var dimensionsText: String? = nil
    var weightKg: Double? = nil

    private enum CodingKeys: String, CodingKey {
        case activeTrackingCarrier
        case activeTrackingNumber
        case originalPackageID = "originalPackageId"
        case originalCarrier
        case originalTrackingNumber
        case originalTrackingURL = "originalTrackingUrl"
        case trackingProvider
        case autoChangedFrom
        case autoChangedTo
        case autoChangedAt
        case senderName
        case swissPostReady
        case expectedDeliveryFrom
        case pickupPoint
        case receiverName
        case dimensionsText
        case weightKg
    }
}

enum FriendsActionResponseInvitationState: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case alreadyAccepted = "already_accepted"
    case alreadyFriends = "already_friends"

    var id: String { rawValue }
}

extension Parcel {
    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        id = try values.decode(UUID.self, forKey: .id)
        trackingNumber = try values.decode(String.self, forKey: .trackingNumber)
        label = try values.decode(String.self, forKey: .label)
        carrier = try values.decode(CarrierID.self, forKey: .carrier)
        createdAt = try values.decode(String.self, forKey: .createdAt)
        expectedDelivery = try values.decodeIfPresent(String.self, forKey: .expectedDelivery)
        lastStatusText = try values.decodeIfPresent(String.self, forKey: .lastStatusText)
        lastSyncedAt = try values.decodeIfPresent(String.self, forKey: .lastSyncedAt)
        syncStatus = try values.decode(SyncStatus.self, forKey: .syncStatus)
        syncError = try values.decodeIfPresent(String.self, forKey: .syncError)
        trackingURL = try values.decodeIfPresent(String.self, forKey: .trackingURL)
        dpdPostcode = try values.decodeIfPresent(String.self, forKey: .dpdPostcode)
        carrierData = try values.decodeIfPresent(CarrierData.self, forKey: .carrierData)
        archivedAt = try values.decodeIfPresent(String.self, forKey: .archivedAt)
        notificationsMuted = try values.decode(Bool.self, forKey: .notificationsMuted)
        trackingEvents = try values.decodeIfPresent([TrackingEvent].self, forKey: .trackingEvents) ?? []
    }
}
